file_importer/config/routes.rb
Rails.application.routes.draw do
  resources :records
  root 'datafiles#index'
  resources :datafiles do
    member { get :records }
  end
end

file_importer/app/models/data_file.rb
class DataFile < ActiveRecord::Base
  has_many :records
end

file_importer/app/models/datafile.rb
class Datafile < ActiveRecord::Base
  validates :filename, uniqueness: true, presence: true
  has_many :records, dependent: :destroy
end

file_importer/app/models/record.rb
require 'csv'

class Record < ActiveRecord::Base
  belongs_to :datafile
  validates :datafile, presence: true

  def self.import(datafile, file)
    FileManager.new(file).unzip_csv(datafile.filename)
    csv_file_path = File.join('/tmp', "#{datafile.filename}.csv")

    CSV.foreach(csv_file_path, headers: true) do |row|
      Record.create! datafile_id: datafile.id,
                     campaign_name: row['campaign_name'],
                     impressions: row['impressions'],
                     clicks: row['clicks'],
                     cost: row['cost'],
                     timestamp: row['timestamp']
    end
  end
end

file_importer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

file_importer/app/controllers/data_files_controller.rb
class DataFilesController < ApplicationController
  before_action :set_data_file, only: [:show, :edit, :update, :destroy, :records]

  # GET /data_files
  def index
    @data_files = DataFile.all
  end

  def records
  end

  # GET /data_files/1
  def show
  end

  # GET /data_files/new
  def new
    @data_file = DataFile.new
  end

  # GET /data_files/1/edit
  def edit
  end

  # POST /data_files
  def create
    @data_file = DataFile.new(filename: params[:file].original_filename)

    if @data_file.save
      Record.import(@data_file, params[:file])
      redirect_to @data_file, notice: 'Data file was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /data_files/1
  def update
    if @data_file.update(data_file_params)
      redirect_to @data_file, notice: 'Data file was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /data_files/1
  def destroy
    @data_file.destroy
    redirect_to data_files_url, notice: 'Data file was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_file
      @data_file = DataFile.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def data_file_params
      params.require(:data_file).permit(:filename)
    end
end

file_importer/app/controllers/datafiles_controller.rb
class DatafilesController < ApplicationController
  before_action :set_datafile, only: [:show, :edit, :update, :destroy, :records]

  def index
    @datafiles = Datafile.all
  end

  def records
  end

  def show
  end

  def new
    @datafile = Datafile.new
  end

  def edit
  end

  def create
    file = datafile_params[:file]
    @datafile = Datafile.new(datafile_params.except(:file))

    if @datafile.save && file.present?
      Record.import(@datafile, file)
      redirect_to datafiles_url, notice: 'Datafile was successfully created.'
    else
      render :new
    end
  end

  def update
    if @datafile.update(datafile_params)
      redirect_to datafiles_url, notice: 'Datafile was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @datafile.destroy
    redirect_to datafiles_url, notice: 'Datafile was successfully destroyed.'
  end

  private

  def set_datafile
    @datafile = Datafile.find(params[:id])
  end

  def datafile_params
    params.require(:datafile).permit(:filename, :file)
  end
end

file_importer/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  def index
    @records = Record.all
  end

  def show
  end

  def new
    @record = Record.new
  end

  def edit
  end

  def create
    @record = Record.new(record_params)

    if @record.save
      redirect_to @record, notice: 'Record was successfully created.'
    else
      render :new
    end
  end

  def update
    if @record.update(record_params)
      redirect_to records_url, notice: 'Record was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @record.destroy
    redirect_to records_url, notice: 'Record was successfully destroyed.'
  end

  private

  def set_record
    @record = Record.find(params[:id])
  end

  def record_params
    params.require(:record).permit(:campaign_name,
                                   :impressions,
                                   :clicks,
                                   :cost,
                                   :timestamp,
                                   :datafile_id
                                  )
  end
end

file_importer/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end
end

file_importer/app/helpers/application_helper.rb
module ApplicationHelper
end

file_importer/app/helpers/data_files_helper.rb
module DataFilesHelper
end

file_importer/app/helpers/datafiles_helper.rb
module DatafilesHelper
end

file_importer/app/helpers/records_helper.rb
module RecordsHelper
end

file_importer/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

file_importer/app/views/data_files/_form.html.erb
<%= form_for(@data_file) do |f| %>
  <% if @data_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_file.errors.count, "error") %> prohibited this data_file from being saved:</h2>

      <ul>
      <% @data_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

file_importer/app/views/data_files/edit.html.erb
<h1>Editing Data File</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_file %> |
<%= link_to 'Back', data_files_path %>

file_importer/app/views/data_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Data Files</h1>

<h4>Import a new file</h4>
<%= form_tag data_files_path, multipart: true, class: 'form-inline' do %>
  <div class="form-group">
    <label for="file">File input</label>
    <%= file_field_tag :file %>
  </div>
  <%= submit_tag "Import file", class: 'btn btn-default' %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Filename</th>
      <th>Records</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_files.each do |data_file| %>
      <tr>
        <td><%= data_file.filename %></td>
        <td><%= link_to 'Records', records_data_file_path(data_file) %></td>
        <td><%= link_to 'Edit', edit_data_file_path(data_file) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

file_importer/app/views/data_files/new.html.erb
<h1>New Data File</h1>

<%= render 'form' %>

<%= link_to 'Back', data_files_path %>

file_importer/app/views/data_files/records.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Records for data file <%=@data_file.filename %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Campaign name</th>
      <th>Impressions</th>
      <th>Clicks</th>
      <th>Cost</th>
      <th>Timestamp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_file.records.each do |record| %>
      <tr>
        <td><%= record.campaign_name %></td>
        <td><%= record.impressions %></td>
        <td><%= record.clicks %></td>
        <td><%= record.cost %></td>
        <td><%= record.timestamp %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

file_importer/app/views/data_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @data_file.filename %>
</p>

<%= link_to 'Edit', edit_data_file_path(@data_file) %> |
<%= link_to 'Back', data_files_path %>

file_importer/app/views/datafiles/_form.html.erb
<%= form_for(datafile) do |f| %>
  <% if datafile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(datafile.errors.count, "error") %> prohibited this datafile from being saved:</h2>

      <ul>
      <% datafile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>

  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

file_importer/app/views/datafiles/edit.html.erb
<h1>Editing Datafile</h1>

<%= render 'form', datafile: @datafile %>

file_importer/app/views/datafiles/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= button_to 'Create a Datafile', { action: :new }, method: :get, class: 'btn btn-primary btn-lg pull-right' %>
</div>

<div>
  <h1>Listing Datafiles</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Filename</th>
        <th colspan="3"></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @datafiles.each do |datafile| %>
        <tr>
          <td><%= datafile.filename %></td>
          <td><%= link_to 'View records', records_datafile_path(datafile) %></td>
          <td><%= link_to 'Destroy', datafile, method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

file_importer/app/views/datafiles/new.html.erb
<h1>New Datafile</h1>

<%= render 'form', datafile: @datafile %>

file_importer/app/views/datafiles/records.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing <%=@datafile.filename %> records</h1>

<table class="table">
  <thead>
    <tr>
      <th>Campaign name</th>
      <th>Impressions</th>
      <th>Clicks</th>
      <th>Cost</th>
      <th>Timestamp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @datafile.records.each do |record| %>
      <tr>
        <td><%= record.campaign_name %></td>
        <td><%= record.impressions %></td>
        <td><%= record.clicks %></td>
        <td><%= record.cost %></td>
        <td><%= record.timestamp %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

file_importer/app/views/datafiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @datafile.filename %>
</p>

<%= link_to 'Edit', edit_datafile_path(@datafile) %> |
<%= link_to 'Back', datafiles_path %>

file_importer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>File Importer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class='navbar navbar-inverse navbar-fixed-top'>
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Home", root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Datafiles', datafiles_path %></li>
          <li><%= link_to 'Records', records_path %></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

file_importer/app/views/records/_form.html.erb
<%= form_for(record) do |f| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :campaign_name %><br>
    <%= f.text_field :campaign_name %>
  </div>
  <div class="field">
    <%= f.label :impressions %><br>
    <%= f.text_field :impressions %>
  </div>
  <div class="field">
    <%= f.label :clicks %><br>
    <%= f.number_field :clicks %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :datafile_id %><br>
    <%= f.text_field :datafile_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

file_importer/app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

file_importer/app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing All Records</h1>

<table class="table">
  <thead>
    <tr>
      <th>Datafile ID</th>
      <th>Campaign name</th>
      <th>Impressions</th>
      <th>Clicks</th>
      <th>Cost</th>
      <th>Timestamp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.datafile_id %></td>
        <td><%= record.campaign_name %></td>
        <td><%= record.impressions %></td>
        <td><%= record.clicks %></td>
        <td><%= record.cost %></td>
        <td><%= record.timestamp %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

file_importer/app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>

file_importer/app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Campaign name:</strong>
  <%= @record.campaign_name %>
</p>

<p>
  <strong>Impressions:</strong>
  <%= @record.impressions %>
</p>

<p>
  <strong>Clicks:</strong>
  <%= @record.clicks %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @record.cost %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @record.timestamp %>
</p>

<p>
  <strong>Datafile:</strong>
  <%= @record.datafile.id %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

file_importer/app/views/static_pages/landing.html.erb
<h1>StaticPages#landing</h1>
<p>Find me in app/views/static_pages/landing.html.erb</p>